### ISSUE TITLE
Bind AVR keywords to KEYAVR

### ISSUE THREAD

**Issue by 4ntoine** [4ntoine/clang#6]
https://github.com/4ntoine/clang/issues/5

I've added `KEYAVR=0x9000` in `lib/Basic/IdentifierTable.cpp`
and add switch case in `GetKeywordStatus()` KS_Enabled, but keywords can't be found:

```
MBA-Anton:bin asmirnov$ ./clang  -c /tmp/avr/Test1.c -I/Applications/avr.app/Contents/Resources/Java/hardware/tools/avr/avr/include -S -emit-llvm -o /tmp/avr/Test1.ll -D__AVR_ATmega168__ --target=avr -O1
/tmp/avr/Test1.c:8:1: error: unknown type name '__flash3'
__flash3 int b = 4;
^
/tmp/avr/Test1.c:8:10: error: expected identifier or '('
__flash3 int b = 4;
         ^
/tmp/avr/Test1.c:12:10: error: use of undeclared identifier 'b'
        int c = b * 57;
                ^
```

**Comment by 4ntoine** [comment]
a bit hacky way but now the keywords expectedly work for AVR target and expectedly not work for others

**Comment by 4ntoine** [comment]
`-triple` should be equal to `"avr"` strictly (to use __flashN keywords)

**Comment by dylanmckay** [comment]
Does this commit mean that we cannot use your fork with any other target than AVR now? I'm not sure I understand

**Comment by 4ntoine** [comment]
__flashN keywords relate to AVR target only. Now you'll get error if using them for non-AVR target which is reasonable (until that commit you could use __flashN for non-AVR targets too which was useless). You can still use my fork for non-AVR targets too (edited my previous comment to remove misunderstanding)
